rundeck {
    org.eclipse.jetty.jaas.spi.LdapLoginModule sufficient
        debug="true"
        contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
        hostname="openldap"
        port="389"
        bindDn="cn=admin,dc=example,dc=com"
        bindPassword="admin123"
        authenticationMethod="simple"
        forceBindingLogin="true"
        userBaseDn="ou=users,dc=example,dc=com"
        userRdnAttribute="uid"
        userIdAttribute="uid"
        userPasswordAttribute="userPassword"
        userObjectClass="inetOrgPerson"
        roleBaseDn="ou=groups,dc=example,dc=com"
        roleNameAttribute="cn"
        roleMemberAttribute="member"
        roleObjectClass="groupOfNames";

    org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
        debug="true"
        file="/home/rundeck/server/config/realm.properties";
};